### ISSUE TITLE
overwrite the text file

### ISSUE THREAD

**Issue by linqing42** [nus-tic4002-AY2021S2/forum#10]
the application should read the existing data in a text file and continue to add new data into the existing file when I rerun it and exit it. However, my application will overwrite and save the latest data instead of continuing the existing data when I rerun and exit. May I know how to fix it?

my storage code link: 
https://github.com/linqing42/ip/blob/master/src/main/java/dukes/storage/Storage.java
my duke code:
https://github.com/linqing42/ip/blob/master/src/main/java/dukes/Duke.java
my exitCommand:
https://github.com/linqing42/ip/blob/master/src/main/java/dukes/command/ExitCommand.java
my ip code:
https://github.com/linqing42/ip

**Comment by damithc** [comment]
@linqing42 when you write to the file, include _all_ data _every time_ (as if you are writing the file for the first time). That way, you will be overwriting the file but there will be no data loss.

**Comment by linqing42** [comment]
> @linqing42 when you write to the file, include _all_ data _every time_ (as if you are writing the file for the first time). That way, you will be overwriting the file but there will be no data loss.

I already include all data but still cannot

**Comment by damithc** [comment]
Looks like a logic problem, to be solved by debugging. 
As it happens, [this topic](https://nus-tic4002-ay2021s2.github.io/website/book/intellij/debuggingBasic/) is among this week's topics. As per that, you can try to use Intellij's debugging feature to find out exactly at which point your code drops the existing data and saves only the new data. Give it a try and let us know if that doesn't lead you to a solution.

**Comment by HongJiancheng** [comment]
Hi @linqing42 ,

I had taken a look at your Storage.java file, the code at line 27 in load method may be the cause of the issue.
![image](https://user-images.githubusercontent.com/43083270/107024492-15729500-67e3-11eb-971e-0456fb9b844f.png)

You can try to command off the line, see if the issue persist.

Thanks!

**Comment by damithc** [comment]
Thanks for the help @HongJiancheng 
@linqing42 So, the loss of data happens at the loading itself, not at the point of _saving_?

**Comment by linqing42** [comment]
> Hi @linqing42 ,
> 
> I had taken a look at your Storage.java file, the code at line 27 in load method may be the cause of the issue.
> ![image](https://user-images.githubusercontent.com/43083270/107024492-15729500-67e3-11eb-971e-0456fb9b844f.png)
> 
> You can try to command off the line, see if the issue persist.
> 
> Thanks!

I remove it, but still cannot.

**Comment by linqing42** [comment]
> Thanks for the help @HongJiancheng
> @linqing42 So, the loss of data happens at the loading itself, not at the point of _saving_?

@damithc I am not sure now. Still cannot

**Comment by damithc** [comment]
@linqing42 This is a logic error, not a technical problem. If we were to help you find the error, we may have to deduct some marks in lieu of it as the correctness of the code is graded. The first step is to find where the data loss happens. e.g., is the existing data never loaded, or it is loaded but deleted afterwards, or is it loaded but never saved, etc. I encourage you to use the intellij debugger to step through your code find where you lose the data. Alternatively (less preferred), you can try to print the number of items in the task list at various points to find where the data loss happens. Once you locate the point of data loss, you'll probably be able to fix it. If still cannot after trying some more, let me know (you can PM me or @boydanderson or both).

**Comment by linqing42** [comment]
> @linqing42 This is a logic error, not a technical problem. If we were to help you find the error, we may have to deduct some marks in lieu of it as the correctness of the code is graded. The first step is to find where the data loss happens. e.g., is the existing data never loaded, or it is loaded but deleted afterwards, or is it loaded but never saved, etc. I encourage you to use the intellij debugger to step through your code find where you lose the data. Alternatively (less preferred), you can try to print the number of items in the task list at various points to find where the data loss happens. Once you locate the point of data loss, you'll probably be able to fix it. If still cannot after trying some more, let me know (you can PM me or @boydanderson or both).

Okay. I try first. If really cannot then I PM you or bodydanderson.
