### ISSUE TITLE
Duke 

### ISSUE THREAD

**Issue by linqing42** [nus-tic4002-AY2021S2/forum#2]
![16116361050253468671408296858504](https://user-images.githubusercontent.com/44344087/105801338-e8003d00-5fd3-11eb-96bb-ec297a302b22.jpg)
![16116361343736257646901074282471](https://user-images.githubusercontent.com/44344087/105801377-f9e1e000-5fd3-11eb-959d-b65ffe919715.jpg)
![16116361890614042998356696753019](https://user-images.githubusercontent.com/44344087/105801438-14b45480-5fd4-11eb-89c6-3d4681bad796.jpg)
![16116362097808081336169622350867](https://user-images.githubusercontent.com/44344087/105801453-1bdb6280-5fd4-11eb-980e-499c247bd23a.jpg)

Hi, Anyone know how to fix this issue under checkstyle.

[This is my code](https://github.com/linqing42/ip/tree/branch-A-Gradle/src/main/java/Dukes) 

Thanks

**Comment by damithc** [comment]
@linqing42 While we wait for someone to offer help, some things you can do:
* Explain exactly after what change this error started popping up
* Give a more explanatory title to the issue

**Comment by GabrielSimbingyang** [comment]
Hi @linqing42,

Ex-student of CS2103T here. I noticed that your IDE is showing you the diamond characters at the bottom of the window. This is an indication of a possible encoding error. 

Would you mind going to Settings -> Editor -> File Encodings -> Project Encoding and set it to "UTF-8" then recompile the program? Let us know if the error message changes afterward!  

Regards,
Gabriel Sim

**Comment by linqing42** [comment]
> @linqing42 While we wait for someone to offer help, some things you can do:
> 
> * Explain exactly after what change this error started popping up
> * Give a more explanatory title to the issue

**Comment by damithc** [comment]
@linqing42 did you manage to solve the problem?

**Comment by linqing42** [comment]
> @linqing42 While we wait for someone to offer help, some things you can do:
> 
> * Explain exactly after what change this error started popping up
> * Give a more explanatory title to the issue

Hi prof, I solved the issue by myself already.

**Comment by linqing42** [comment]
> @linqing42 did you manage to solve the problem?

@damithc  solved.

**Comment by linqing42** [comment]
> Hi @linqing42,
> 
> Ex-student of CS2103T here. I noticed that your IDE is showing you the diamond characters at the bottom of the window. This is an indication of a possible encoding error.
> 
> Would you mind going to Settings -> Editor -> File Encodings -> Project Encoding and set it to "UTF-8" then recompile the program? Let us know if the error message changes afterward!
> 
> Regards,
> Gabriel Sim

@GabrielSimbingyang  the file encoding is correct. But I solve it already. thanks a lot. Actually, it is under the CheckStyle issue.  as well.

**Comment by damithc** [comment]
Thanks @GabrielSimbingyang for the inputs.
