### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: MainWindow

### ISSUE THREAD

**Issue by tototto** [nus-tic4002-AY2021S2/forum#3]
I encountered an issue while trying to build my iP project using FXML

The problem seems to be that intelliJ Cannot resolve class 'MainWindow' in MainWindow.fxml

The error i received is "Caused by: java.lang.ClassNotFoundException: MainWindow"

![image](https://user-images.githubusercontent.com/43071400/105957501-4f8db980-60b4-11eb-80c4-230974fce5b7.png)

The other method used are also not recognised.
![image](https://user-images.githubusercontent.com/43071400/105958009-00945400-60b5-11eb-98c4-b611640cf7c6.png)

I am unable to relate the dependency. I tried this on the 4th tutorial and it is working on a clean and brand new project.

May I know how I may do so?

**Comment by damithc** [comment]
Quick check: is your `MainWindow` class inside a package?

**Comment by tototto** [comment]
my ```MainWindow.java``` is under the duke package

![image](https://user-images.githubusercontent.com/43071400/105960252-e9a33100-60b7-11eb-973d-eddcb9548c24.png)

**Comment by damithc** [comment]
see if using  `duke.MainWindow` in the fxml file works

**Comment by tototto** [comment]
@damithc the fix got rid of that error but introduced a new fxml error

Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,6]

**Comment by damithc** [comment]
@tototto push the code so that someone can take a look?

**Comment by tototto** [comment]
@damithc I managed to fix the issue. 

it is due to some extra FXML tag. 

I am posting a working copy of the FXML file incase anyone encounters similar issues

```
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.control.*?>
<?import javafx.scene.layout.*?>

<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="duke.MainWindow">
    <children>
        <TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0" AnchorPane.bottomAnchor="1.0" />
        <Button fx:id="sendButton" layoutX="324.0" layoutY="558.0" mnemonicParsing="false" onAction="#handleUserInput" prefHeight="41.0" prefWidth="76.0" text="Send" />
        <ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0" prefHeight="557.0" prefWidth="400.0" vvalue="1.0">
            <content>
                <VBox fx:id="dialogContainer" prefHeight="552.0" prefWidth="388.0" />
            </content>
        </ScrollPane>
    </children>
</AnchorPane>
```

**Comment by tototto** [comment]
this thread's issue is for MainWindow.fxml
