### ISSUE TITLE
FXML UI output is truncated

### ISSUE THREAD

**Issue by tototto** [nus-tic4002-AY2021S2/forum#4]
Hi.

I encountered an issue in MainWindow.fxml and modified it to work in 
https://github.com/nus-tic4002-AY2021S2/forum/issues/3

However, after modification, the output of my duke program end up being truncated. although the data return is correct (captured in CLI)

![image](https://user-images.githubusercontent.com/43071400/105977266-1feaab80-60cc-11eb-94f6-116dd828783b.png)

**Comment by tototto** [comment]
It appears to unable to display anything beyond the height of the display picture

**Comment by damithc** [comment]
See if this helps https://github.com/nus-cs2103-AY2021S1/forum/issues/125

**Comment by tototto** [comment]
Thank you, this resolved my problem.
