### ISSUE TITLE
Task :checkstyleMain FAILED FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by tototto** [nus-tic4002-AY2021S2/forum#7]
Hi , i am trying to run CI with Duke with GitHub actions.

I am able to build and run my on my local with no issue 
There was no build issue on my local for involving checkstyle and i was able to run it.
However build on CI failed.

![image](https://user-images.githubusercontent.com/43071400/106374730-af3fd980-63c0-11eb-9642-0b53f6555293.png)

**Comment by damithc** [comment]
1. Are you able to run the `checkstyleMain` gradle task locally?
1. Have you committed and pushed the checkstyle config files?

**Comment by tototto** [comment]
For (2) i have pushed the checkstyle config file 
![image](https://user-images.githubusercontent.com/43071400/106375620-8f141880-63c8-11eb-8128-52638924ea06.png)

For (1) I encountered the 2 errors when running ```checkstyleMain ``` gradle task locally. I do not understand what the root cause of the error is
![image](https://user-images.githubusercontent.com/43071400/106375658-e74b1a80-63c8-11eb-918e-930d209546ca.png)

**Comment by damithc** [comment]
See if https://github.com/nus-cs2103-AY2021S2/forum/issues/76 helps
