### ISSUE TITLE
CI result fail: Fail at Setup JDK 11 with Error: The operation was canceled.

### ISSUE THREAD

**Issue by SJZheng-Abel** [nus-tic4002-AY2021S2/forum#9]
Hi Prof and Boyd:

I'm currently doing the task of add A-CI and noticed I always got a fail result at Setup JDK 11 shown as below:
![image](https://user-images.githubusercontent.com/43492731/106743454-5f2f7400-6659-11eb-9370-537ce2537439.png)

I'm using Windows system and gradle.yml is strictly follows the sample given, which the part of Setup JDK 11 is shown below: 
![image](https://user-images.githubusercontent.com/43492731/106743560-87b76e00-6659-11eb-98c1-dae9403b0fc4.png)

My ip repo link is: 
https://github.com/ZhengShijieNUS/ip

And I've done checking on the project setting and Intellij settings and so on. I'm pretty sure I'm using JDK 11 for the IP.

Please kindly help to advise what I should do now to fix the issue. 

And also please let me know if you require more details on other aspects.

**Comment by Jh123x** [comment]
Hi @ZhengShijieNUS , I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems)

![image](https://user-images.githubusercontent.com/10459011/106748970-f0eeaf80-6660-11eb-854e-587b6c9400ea.png)
Judging from the current error message in your ip, can you try changing the gradlew file permission on the git repository to make it executable using this command:

`git update-index --chmod=+x gradlew`
and commit it?


Source [here](https://stackoverflow.com/questions/58282791/why-when-i-use-github-actions-ci-for-a-gradle-project-i-face-gradlew-permiss)

**Comment by SJZheng-Abel** [comment]
Hi @Jh123x 

Thank you very much. It works for me and now everything goes fine.
